name: Metrics
on:
  # Schedule hourly updates
  schedule: [{cron: "0 * * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Target your GitHub username to get stats from all repositories
          user: mgeorge67701
          # Include all repositories (public and private if token has access)
          repositories_batch: 1000
          repositories_forks: yes
          repositories_affiliations: owner, collaborator, organization_member
          # Include commits from all your email addresses
          commits_authoring: georgmohan@gmail.com, mohan.george@bottomline.com, georgemohan@gmail.com
          # Only show basic metrics summary (no detailed activity)
          base: header, community, repositories, metadata
          # Disable activity plugin to avoid showing individual commits
          plugin_activity: no
