# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Base Metrics

on:
  # Schedule updates (each day at midnight)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  base-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: mgeorge67701
          template: classic
          filename: metrics-base.svg
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/London
          # Scan all repositories for comprehensive activity
          repositories_batch: 100
          repositories_forks: yes
          repositories_affiliations: owner, collaborator, organization_member
          # Include commits from all your email addresses
          commits_authoring: georgmohan@gmail.com, mohan.george@bottomline.com, georgemohan@gmail.com
