# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Base Metrics

on:
  # Schedule updates (each day at midnight)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  base-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: mgeorge67701
          template: classic
          filename: metrics-base.svg
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/London
          
          # Repository settings for comprehensive analysis
          repositories_batch: 200
          repositories_forks: yes
          repositories_affiliations: owner, collaborator, organization_member
          repositories_skipped: |
            */.github
          
          # Ensure comprehensive commit tracking
          config_order: base.header, base.activity, base.community, base.repositories, base.metadata
          
          # Followup plugin for commit statistics and repository health
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          plugin_followup_indepth: yes
          plugin_followup_archived: yes
          
          # Stargazers plugin for repository popularity
          plugin_stargazers: yes
          plugin_stargazers_charts: yes
          plugin_stargazers_charts_type: classic
          plugin_stargazers_days: 30
          
          # Reactions plugin for interaction statistics
          plugin_reactions: yes
          plugin_reactions_limit: 200
          plugin_reactions_days: 30
          plugin_reactions_details: percentage
          plugin_reactions_ignored: github-actions
          
          # Isocalendar plugin for contribution calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          # People plugin for collaboration statistics
          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_identicons: yes
          plugin_people_types: followers, following
          plugin_people_thanks: yes
          
          # Gists plugin for gist statistics
          plugin_gists: yes
          
          # Repositories plugin for repository statistics
          plugin_repositories: yes
          plugin_repositories_order: featured, pinned, starred, random
          plugin_repositories_featured: mgeorge67701/mgeorge67701
          plugin_repositories_pinned: 3
          plugin_repositories_starred: 3
          plugin_repositories_random: 2
          
          # Languages plugin for enhanced visualization
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 30
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used, recently-used
          plugin_languages_threshold: 0%
          
          # Achievements plugin
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          
          # Activity plugin for contribution patterns - Enhanced for commit tracking
          plugin_activity: yes
          plugin_activity_days: 365
          plugin_activity_filter: all
          plugin_activity_limit: 50
          plugin_activity_load: 500
          plugin_activity_visibility: all
          plugin_activity_timestamps: yes
          
          # Calendar plugin for contribution calendar
          plugin_calendar: yes
          plugin_calendar_limit: 0
          
          # Habits plugin for coding habits analysis - Extended for comprehensive tracking
          plugin_habits: yes
          plugin_habits_days: 365
          plugin_habits_facts: yes
          plugin_habits_from: 2000
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          plugin_habits_charts: yes
          
          # Notable plugin for notable contributions
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_repositories: yes
          plugin_notable_indepth: yes
          plugin_notable_types: commit, issue, pull_request
          
          # Traffic plugin for repository traffic
          plugin_traffic: yes
          
          # Lines of code plugin for code statistics
          plugin_lines: yes
          plugin_lines_history_limit: 5
          plugin_lines_sections: base, repositories, history
          plugin_lines_repositories_limit: 10
          
          # Reliability and performance settings
          retries: 5
          retries_delay: 300
          retries_output_action: 5
          
          # Display settings for enhanced view
          config_display: large
          config_padding: 0, 8 + 11%
          config_output: auto
          config_animations: yes
