# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Base Metrics

on:
  # Schedule updates (each day at midnight)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  base-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: mgeorge67701
          template: classic
          filename: metrics-base.svg
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/London
          # Simplified configuration for stability
          repositories_batch: 50
          repositories_forks: yes
          # Add timeout settings for reliability
          config_timeout: 30
          retries: 3
