# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Base Metrics

on:
  # Schedule updates (every day at midnight)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  base-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: mgeorge67701
          template: classic
          filename: metrics-base.svg
          base: activity, community, repositories, metadata
          config_timezone: Europe/London
          
          # Repository settings for comprehensive analysis
          repositories_batch: 200
          repositories_forks: yes
          repositories_affiliations: owner, collaborator, organization_member
          
          # Languages plugin for basic language statistics
          plugin_languages: yes
          plugin_languages_limit: 0
          plugin_languages_threshold: 0%
          plugin_languages_categories: programming, markup, data, prose, other
          plugin_languages_other: yes
          plugin_languages_sections:  unused, other, data
          plugin_languages_ignored: ''
          plugin_languages_skipped: ''
          plugin_languages_analysis_timeout: 300
          
          # Reliability and performance settings
          retries: 3
          retries_delay: 300